### ISSUE TITLE
Meet with Amadeus

### ISSUE THREAD

**Issue by aixi-mfisher** [aixi-mfisher/tasks#6]
traveling salesman on crack problem

**Comment by AIXI-CO** [comment]
WHAT WE LEARNED:

It was great talking to you!  Let me go through the calculation using American Airlines as an example.  I’ll also pick 2019 as a reference year (i.e., pre-COVID). 

 

Passenger revenue for AA in 2019: $45.77 billion.  Source:  Google.

 

American Airline Revenue 2019

In the fiscal year of 2019, the U.S. airline reported around 45.77 billion U.S. dollars in operating revenue. Two years later, operating revenue declined to about 29.9 billion U.S. dollars as a result of the large global decrease in flight operations caused by the COVID-19 pandemic.Mar 11, 2022

 

Average aircraft utilization of AA aircraft across the whole fleet in 2019: 9.46 hours.  Note: aircraft utilization is total block time spent on average across all equipment for a specific time period and is expressed in hours per day.  Source: MIT’s Airline Data Project.  Link: https://web.mit.edu/airlinedata/www/2020%2012%20Month%20Documents/Aircraft%20and%20Related/Carrier%20Operating%20Stats/American%20Airlines%20Aircraft%20Operating%20Statistics-%20Actuals.htm

 

So average value of each available hour per day across all aircraft in AA’s fleet in 2019 is $45.77 billion / 9.46 hours is $4.84 billion / hour.  Expressed per minute is $4.84 billion / 60 minutes per hour is thus $80.6 million in annual revenue per available minute.  Note that the aircraft utilization figure does not include time spent on the ground at airports, it’s really available time for the aircraft to generate revenue.  The assumption is that you’ll find more minutes each day for every aircraft which could put to productive use.  This extra revenue comes from the airlines ability to use this extra time to either squeeze out more aircraft units from a specific schedule (unlikely, but possible), or be able to fly more flights, or leave at better times for their customers.  It’s obviously an average figure and some airlines might quibble over whether the average reflects the margin, but generally will be correct for an order of magnitude.

 

It should be easy to go through this same calculation for different airlines and/or years.  It also might make sense to look at specific aircraft types rather than considering the fleet as a whole.

 

I hope this helps!

 

Jim
